import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/nav-bar";
import Footer from "@/components/footer";
// import { ModalProvider } from "@/components/providers/ModalProvider";
import { Toaster } from "sonner";
import { Poppins } from "next/font/google";
import { QueryClient } from "@tanstack/react-query";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Navbar />
        {/* <ModalProvider /> */}
        <main className="w-full min-h-screen">{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
